# Generated by savvy: do not edit by hand
#
# Note:
#   This wrapper file is named as `000-wrappers.R` so that this file is loaded
#   first, which allows users to override the functions defined here (e.g., a
#   print() method for an enum).

#' @useDynLib maplibr, .registration = TRUE
#' @keywords internal
NULL

# Check class and extract the external pointer embedded in the environment
.savvy_extract_ptr <- function(e, class) {
  if(is.null(e)) {
    return(NULL)
  }

  if(inherits(e, class)) {
    e$.ptr
  } else {
    msg <- paste0("Expected ", class, ", got ", class(e)[1])
    stop(msg, call. = FALSE)
  }
}

# Prohibit modifying environments

#' @export
`$<-.savvy_maplibr__sealed` <- function(x, name, value) {
  class <- gsub("__bundle$", "", class(x)[1])
  stop(class, " cannot be modified", call. = FALSE)
}

#' @export
`[[<-.savvy_maplibr__sealed` <- function(x, i, value) {
  class <- gsub("__bundle$", "", class(x)[1])
  stop(class, " cannot be modified", call. = FALSE)
}

#' Build a small hardcoded i32 Series in Rust and stream it out to R
#' through the Arrow C Stream Interface.
#'
#' @param stream_ptr An external pointer from `nanoarrow::nanoarrow_allocate_array_stream()`.
#' @export
`export_test_series` <- function(`stream_ptr`) {
  invisible(.Call(savvy_export_test_series__impl, `stream_ptr`))
}

#' Build the `build_test_solution_mappings()` fixture and stream it out via
#' `export_solution_mappings` -- proving the DataFrame case reuses the
#' Series-level mechanism unchanged, against a fixture with a genuinely
#' multi-typed column (see `build_test_solution_mappings`'s doc comment).
#'
#' @param stream_ptr An external pointer from `nanoarrow::nanoarrow_allocate_array_stream()`.
#' @returns The `rdf_node_types` side-channel, as a JSON string.
#' @export
`export_test_solution_mappings` <- function(`stream_ptr`) {
  .Call(savvy_export_test_solution_mappings__impl, `stream_ptr`)
}

#' Read an Arrow C stream from R back into a Rust Series, then hand back
#' its length and first value as a sanity check (i32 only, for this prototype).
#'
#' @param stream_ptr An external pointer holding a filled ArrowArrayStream.
#' @returns An integer vector: `c(length, first_value)`.
#' @export
`import_test_series` <- function(`stream_ptr`) {
  .Call(savvy_import_test_series__impl, `stream_ptr`)
}

#' Read an Arrow C stream from R back into a Struct-typed Series, unnest it
#' back into a DataFrame (`StructChunked::unnest`, the reverse of
#' `into_struct`), and return a small human-readable summary combining the
#' recovered DataFrame's shape with the `rdf_node_types` JSON side-channel
#' handed back in -- a sanity check that both halves survive the round trip
#' together, matching `import_test_series`'s role for the Series-only case.
#'
#' @param stream_ptr An external pointer holding a filled ArrowArrayStream.
#' @param rdf_node_types_json The JSON string returned by
#'   `export_test_solution_mappings`.
#' @returns A character vector: one line per column, `"<name>: <dtype> [<rdf types>]"`.
#' @export
`import_test_solution_mappings` <- function(`stream_ptr`, `rdf_node_types_json`) {
  .Call(savvy_import_test_solution_mappings__impl, `stream_ptr`, `rdf_node_types_json`)
}

#' Build an rdf:type-style Triple instance (mirrors py_maplib's `Triple()`
#' helper, lib/templates/src/python.rs:404-417).
#'
#' @export
`make_triple` <- function(`subject`, `predicate`, `object`, `list_expander` = NULL) {
  `subject` <- .savvy_extract_ptr(`subject`, "maplibr::RArgument")
  `predicate` <- .savvy_extract_ptr(`predicate`, "maplibr::RArgument")
  `object` <- .savvy_extract_ptr(`object`, "maplibr::RArgument")
  .savvy_wrap_RInstance(.Call(savvy_make_triple__impl, `subject`, `predicate`, `object`, `list_expander`))
}

#' Validate a blank node identifier's syntax (mirrors oxrdf::BlankNode::new,
#' used by py_maplib's PyBlankNode::new, lib/representation/src/python.rs:531-535).
#' Raises an R error on invalid syntax; returns nothing on success.
#'
#' @param id Blank node identifier, without the leading `_:`.
#' @export
`validate_blank_node_id` <- function(`id`) {
  invisible(.Call(savvy_validate_blank_node_id__impl, `id`))
}

#' Validate an IRI's syntax (mirrors oxrdf::NamedNode::new, the same check
#' py_maplib's PyIRI::new uses, lib/representation/src/python.rs:279-282).
#' Raises an R error on invalid syntax; returns nothing on success.
#'
#' @param iri IRI string to validate.
#' @export
`validate_iri` <- function(`iri`) {
  invisible(.Call(savvy_validate_iri__impl, `iri`))
}

#' Validate a SPARQL variable name's syntax (mirrors oxrdf::Variable::new,
#' used by py_maplib's PyVariable::new, lib/representation/src/python.rs:340-343).
#' Raises an R error on invalid syntax; returns nothing on success.
#'
#' @param name Variable name, without the leading `?`/`$`.
#' @export
`validate_variable_name` <- function(`name`) {
  invisible(.Call(savvy_validate_variable_name__impl, `name`))
}

### wrapper functions for RArgument


`.savvy_wrap_RArgument` <- function(ptr) {
  e <- new.env(parent = emptyenv())
  e$.ptr <- ptr


  class(e) <- c("maplibr::RArgument", "RArgument", "savvy_maplibr__sealed")
  e
}


#' An OTTR argument: a Variable, or a constant term (IRI/BlankNode/Literal/none).
#' Mirrors py_maplib's `Argument` (lib/templates/src/python.rs:203-236).
#'
#' @export
`RArgument` <- new.env(parent = emptyenv())

### associated functions for RArgument

`RArgument`$`from_constant_term` <- function(`term`, `list_expand`) {
  `term` <- .savvy_extract_ptr(`term`, "maplibr::RConstantTerm")
  .savvy_wrap_RArgument(.Call(savvy_RArgument_from_constant_term__impl, `term`, `list_expand`))
}

`RArgument`$`from_variable` <- function(`name`, `list_expand`) {
  .savvy_wrap_RArgument(.Call(savvy_RArgument_from_variable__impl, `name`, `list_expand`))
}


class(`RArgument`) <- c("maplibr::RArgument__bundle", "savvy_maplibr__sealed")

#' @export
`print.maplibr::RArgument__bundle` <- function(x, ...) {
  cat('maplibr::RArgument\n')
}

### wrapper functions for RConstantTerm


`.savvy_wrap_RConstantTerm` <- function(ptr) {
  e <- new.env(parent = emptyenv())
  e$.ptr <- ptr


  class(e) <- c("maplibr::RConstantTerm", "RConstantTerm", "savvy_maplibr__sealed")
  e
}


#' An OTTR constant term: an IRI, blank node, literal, or explicit "none".
#' Mirrors py_maplib's `extract_constant_term` (lib/templates/src/python.rs:434-446).
#'
#' @export
`RConstantTerm` <- new.env(parent = emptyenv())

### associated functions for RConstantTerm

`RConstantTerm`$`blank_node` <- function(`id`) {
  .savvy_wrap_RConstantTerm(.Call(savvy_RConstantTerm_blank_node__impl, `id`))
}

`RConstantTerm`$`iri` <- function(`iri`) {
  .savvy_wrap_RConstantTerm(.Call(savvy_RConstantTerm_iri__impl, `iri`))
}

`RConstantTerm`$`literal` <- function(`value`, `datatype_iri`, `language` = NULL) {
  .savvy_wrap_RConstantTerm(.Call(savvy_RConstantTerm_literal__impl, `value`, `datatype_iri`, `language`))
}

`RConstantTerm`$`none` <- function() {
  .savvy_wrap_RConstantTerm(.Call(savvy_RConstantTerm_none__impl))
}


class(`RConstantTerm`) <- c("maplibr::RConstantTerm__bundle", "savvy_maplibr__sealed")

#' @export
`print.maplibr::RConstantTerm__bundle` <- function(x, ...) {
  cat('maplibr::RConstantTerm\n')
}

### wrapper functions for RInstance

`RInstance_iri` <- function(self) {
  function() {
    .Call(savvy_RInstance_iri__impl, `self`)
  }
}

`.savvy_wrap_RInstance` <- function(ptr) {
  e <- new.env(parent = emptyenv())
  e$.ptr <- ptr
  e$`iri` <- `RInstance_iri`(ptr)

  class(e) <- c("maplibr::RInstance", "RInstance", "savvy_maplibr__sealed")
  e
}


#' An OTTR template instance: a call to a template with concrete arguments.
#' Mirrors py_maplib's `Instance` (lib/templates/src/python.rs:245-288).
#'
#' @export
`RInstance` <- new.env(parent = emptyenv())

### associated functions for RInstance

`RInstance`$`new` <- function(`template_iri`, `arguments`, `list_expander` = NULL) {
  .savvy_wrap_RInstance(.Call(savvy_RInstance_new__impl, `template_iri`, `arguments`, `list_expander`))
}


class(`RInstance`) <- c("maplibr::RInstance__bundle", "savvy_maplibr__sealed")

#' @export
`print.maplibr::RInstance__bundle` <- function(x, ...) {
  cat('maplibr::RInstance\n')
}

### wrapper functions for RModel

`RModel_add_graph` <- function(self) {
  function(`other`, `source_graph` = NULL, `target_graph` = NULL) {
    `other` <- .savvy_extract_ptr(`other`, "maplibr::RModel")
    invisible(.Call(savvy_RModel_add_graph__impl, `self`, `other`, `source_graph`, `target_graph`))
  }
}

`RModel_add_prefixes` <- function(self) {
  function(`prefixes`) {
    invisible(.Call(savvy_RModel_add_prefixes__impl, `self`, `prefixes`))
  }
}

`RModel_add_template` <- function(self) {
  function(`template`) {
    `template` <- .savvy_extract_ptr(`template`, "maplibr::RTemplate")
    invisible(.Call(savvy_RModel_add_template__impl, `self`, `template`))
  }
}

`RModel_add_template_string` <- function(self) {
  function(`doc`) {
    .Call(savvy_RModel_add_template_string__impl, `self`, `doc`)
  }
}

`RModel_compact` <- function(self) {
  function() {
    invisible(.Call(savvy_RModel_compact__impl, `self`))
  }
}

`RModel_create_index` <- function(self) {
  function() {
    invisible(.Call(savvy_RModel_create_index__impl, `self`))
  }
}

`RModel_detach_graph` <- function(self) {
  function(`preserve_name`, `graph` = NULL) {
    .savvy_wrap_RModel(.Call(savvy_RModel_detach_graph__impl, `self`, `preserve_name`, `graph`))
  }
}

`RModel_infer_rdfs` <- function(self) {
  function(`graph` = NULL) {
    .Call(savvy_RModel_infer_rdfs__impl, `self`, `graph`)
  }
}

`RModel_map` <- function(self) {
  function(`template_iri`, `stream_ptr`, `graph` = NULL, `validate_iris` = NULL) {
    invisible(.Call(savvy_RModel_map__impl, `self`, `template_iri`, `stream_ptr`, `graph`, `validate_iris`))
  }
}

`RModel_map_no_data` <- function(self) {
  function(`template_iri`, `graph` = NULL, `validate_iris` = NULL) {
    invisible(.Call(savvy_RModel_map_no_data__impl, `self`, `template_iri`, `graph`, `validate_iris`))
  }
}

`RModel_query` <- function(self) {
  function(`sparql`, `stream_ptr`, `include_transient`, `graph` = NULL) {
    .Call(savvy_RModel_query__impl, `self`, `sparql`, `stream_ptr`, `include_transient`, `graph`)
  }
}

`RModel_reads` <- function(self) {
  function(`s`, `format`, `graph` = NULL) {
    invisible(.Call(savvy_RModel_reads__impl, `self`, `s`, `format`, `graph`))
  }
}

`RModel_serialize` <- function(self) {
  function(`path`) {
    invisible(.Call(savvy_RModel_serialize__impl, `self`, `path`))
  }
}

`RModel_size` <- function(self) {
  function(`graph` = NULL) {
    .Call(savvy_RModel_size__impl, `self`, `graph`)
  }
}

`RModel_truncate_graph` <- function(self) {
  function(`graph` = NULL) {
    invisible(.Call(savvy_RModel_truncate_graph__impl, `self`, `graph`))
  }
}

`RModel_writes` <- function(self) {
  function(`format` = NULL, `graph` = NULL) {
    .Call(savvy_RModel_writes__impl, `self`, `format`, `graph`)
  }
}

`.savvy_wrap_RModel` <- function(ptr) {
  e <- new.env(parent = emptyenv())
  e$.ptr <- ptr
  e$`add_graph` <- `RModel_add_graph`(ptr)
  e$`add_prefixes` <- `RModel_add_prefixes`(ptr)
  e$`add_template` <- `RModel_add_template`(ptr)
  e$`add_template_string` <- `RModel_add_template_string`(ptr)
  e$`compact` <- `RModel_compact`(ptr)
  e$`create_index` <- `RModel_create_index`(ptr)
  e$`detach_graph` <- `RModel_detach_graph`(ptr)
  e$`infer_rdfs` <- `RModel_infer_rdfs`(ptr)
  e$`map` <- `RModel_map`(ptr)
  e$`map_no_data` <- `RModel_map_no_data`(ptr)
  e$`query` <- `RModel_query`(ptr)
  e$`reads` <- `RModel_reads`(ptr)
  e$`serialize` <- `RModel_serialize`(ptr)
  e$`size` <- `RModel_size`(ptr)
  e$`truncate_graph` <- `RModel_truncate_graph`(ptr)
  e$`writes` <- `RModel_writes`(ptr)

  class(e) <- c("maplibr::RModel", "RModel", "savvy_maplibr__sealed")
  e
}


#' A maplib knowledge graph model.
#'
#' @export
`RModel` <- new.env(parent = emptyenv())

### associated functions for RModel

`RModel`$`deserialize` <- function(`path`, `storage_folder` = NULL) {
  .savvy_wrap_RModel(.Call(savvy_RModel_deserialize__impl, `path`, `storage_folder`))
}

`RModel`$`new` <- function() {
  .savvy_wrap_RModel(.Call(savvy_RModel_new__impl))
}


class(`RModel`) <- c("maplibr::RModel__bundle", "savvy_maplibr__sealed")

#' @export
`print.maplibr::RModel__bundle` <- function(x, ...) {
  cat('maplibr::RModel\n')
}

### wrapper functions for RParameter


`.savvy_wrap_RParameter` <- function(ptr) {
  e <- new.env(parent = emptyenv())
  e$.ptr <- ptr


  class(e) <- c("maplibr::RParameter", "RParameter", "savvy_maplibr__sealed")
  e
}


#' An OTTR template parameter. Mirrors py_maplib's `Parameter`
#' (lib/templates/src/python.rs:21-167) -- `rdf_type` here only supports a
#' basic (non-nested, non-list) RDF type, given as a datatype/class IRI
#' string; PType::Lub/List/NEList and RDFType.Nested()/Multi() are not yet
#' ported (they need the RDFType port, maplib-snz's remaining scope).
#'
#' @export
`RParameter` <- new.env(parent = emptyenv())

### associated functions for RParameter

`RParameter`$`new` <- function(`variable_name`, `optional`, `allow_blank`, `rdf_type_iri` = NULL, `default_value` = NULL) {
  `default_value` <- .savvy_extract_ptr(`default_value`, "maplibr::RConstantTerm")
  .savvy_wrap_RParameter(.Call(savvy_RParameter_new__impl, `variable_name`, `optional`, `allow_blank`, `rdf_type_iri`, `default_value`))
}


class(`RParameter`) <- c("maplibr::RParameter__bundle", "savvy_maplibr__sealed")

#' @export
`print.maplibr::RParameter__bundle` <- function(x, ...) {
  cat('maplibr::RParameter\n')
}

### wrapper functions for RTemplate

`RTemplate_instance` <- function(self) {
  function(`arguments`, `list_expander` = NULL) {
    .savvy_wrap_RInstance(.Call(savvy_RTemplate_instance__impl, `self`, `arguments`, `list_expander`))
  }
}

`RTemplate_iri` <- function(self) {
  function() {
    .Call(savvy_RTemplate_iri__impl, `self`)
  }
}

`RTemplate_print_string` <- function(self) {
  function() {
    .Call(savvy_RTemplate_print_string__impl, `self`)
  }
}

`.savvy_wrap_RTemplate` <- function(ptr) {
  e <- new.env(parent = emptyenv())
  e$.ptr <- ptr
  e$`instance` <- `RTemplate_instance`(ptr)
  e$`iri` <- `RTemplate_iri`(ptr)
  e$`print_string` <- `RTemplate_print_string`(ptr)

  class(e) <- c("maplibr::RTemplate", "RTemplate", "savvy_maplibr__sealed")
  e
}


#' An OTTR template: a named, parameterized set of instance patterns.
#' Mirrors py_maplib's `Template` (lib/templates/src/python.rs:291-402).
#'
#' @export
`RTemplate` <- new.env(parent = emptyenv())

### associated functions for RTemplate

`RTemplate`$`new` <- function(`iri`, `parameters`, `instances`) {
  .savvy_wrap_RTemplate(.Call(savvy_RTemplate_new__impl, `iri`, `parameters`, `instances`))
}


class(`RTemplate`) <- c("maplibr::RTemplate__bundle", "savvy_maplibr__sealed")

#' @export
`print.maplibr::RTemplate__bundle` <- function(x, ...) {
  cat('maplibr::RTemplate\n')
}

