# Generated by savvy: do not edit by hand
#
# Note:
#   This wrapper file is named as `000-wrappers.R` so that this file is loaded
#   first, which allows users to override the functions defined here (e.g., a
#   print() method for an enum).

#' @useDynLib maplibr, .registration = TRUE
#' @keywords internal
NULL

# Check class and extract the external pointer embedded in the environment
.savvy_extract_ptr <- function(e, class) {
  if(is.null(e)) {
    return(NULL)
  }

  if(inherits(e, class)) {
    e$.ptr
  } else {
    msg <- paste0("Expected ", class, ", got ", class(e)[1])
    stop(msg, call. = FALSE)
  }
}

# Prohibit modifying environments

#' @export
`$<-.savvy_maplibr__sealed` <- function(x, name, value) {
  class <- gsub("__bundle$", "", class(x)[1])
  stop(class, " cannot be modified", call. = FALSE)
}

#' @export
`[[<-.savvy_maplibr__sealed` <- function(x, i, value) {
  class <- gsub("__bundle$", "", class(x)[1])
  stop(class, " cannot be modified", call. = FALSE)
}

#' Build a small hardcoded i32 Series in Rust and stream it out to R
#' through the Arrow C Stream Interface.
#'
#' @param stream_ptr An external pointer from `nanoarrow::nanoarrow_allocate_array_stream()`.
#' @export
`export_test_series` <- function(`stream_ptr`) {
  invisible(.Call(savvy_export_test_series__impl, `stream_ptr`))
}

#' Read an Arrow C stream from R back into a Rust Series, then hand back
#' its length and first value as a sanity check (i32 only, for this prototype).
#'
#' @param stream_ptr An external pointer holding a filled ArrowArrayStream.
#' @returns An integer vector: `c(length, first_value)`.
#' @export
`import_test_series` <- function(`stream_ptr`) {
  .Call(savvy_import_test_series__impl, `stream_ptr`)
}

### wrapper functions for RModel

`RModel_size` <- function(self) {
  function() {
    .Call(savvy_RModel_size__impl, `self`)
  }
}

`.savvy_wrap_RModel` <- function(ptr) {
  e <- new.env(parent = emptyenv())
  e$.ptr <- ptr
  e$`size` <- `RModel_size`(ptr)

  class(e) <- c("maplibr::RModel", "RModel", "savvy_maplibr__sealed")
  e
}


#' A maplib knowledge graph model.
#'
#' @export
`RModel` <- new.env(parent = emptyenv())

### associated functions for RModel

`RModel`$`new` <- function() {
  .savvy_wrap_RModel(.Call(savvy_RModel_new__impl))
}


class(`RModel`) <- c("maplibr::RModel__bundle", "savvy_maplibr__sealed")

#' @export
`print.maplibr::RModel__bundle` <- function(x, ...) {
  cat('maplibr::RModel\n')
}

