# Generated by savvy: do not edit by hand
#
# Note:
#   This wrapper file is named as `000-wrappers.R` so that this file is loaded
#   first, which allows users to override the functions defined here (e.g., a
#   print() method for an enum).

#' @useDynLib maplibr, .registration = TRUE
#' @keywords internal
NULL

# Check class and extract the external pointer embedded in the environment
.savvy_extract_ptr <- function(e, class) {
  if(is.null(e)) {
    return(NULL)
  }

  if(inherits(e, class)) {
    e$.ptr
  } else {
    msg <- paste0("Expected ", class, ", got ", class(e)[1])
    stop(msg, call. = FALSE)
  }
}

# Prohibit modifying environments

#' @export
`$<-.savvy_maplibr__sealed` <- function(x, name, value) {
  class <- gsub("__bundle$", "", class(x)[1])
  stop(class, " cannot be modified", call. = FALSE)
}

#' @export
`[[<-.savvy_maplibr__sealed` <- function(x, i, value) {
  class <- gsub("__bundle$", "", class(x)[1])
  stop(class, " cannot be modified", call. = FALSE)
}

#' Build a small hardcoded i32 Series in Rust and stream it out to R
#' through the Arrow C Stream Interface.
#'
#' @param stream_ptr An external pointer from `nanoarrow::nanoarrow_allocate_array_stream()`.
#' @export
`export_test_series` <- function(`stream_ptr`) {
  invisible(.Call(savvy_export_test_series__impl, `stream_ptr`))
}

#' Read an Arrow C stream from R back into a Rust Series, then hand back
#' its length and first value as a sanity check (i32 only, for this prototype).
#'
#' @param stream_ptr An external pointer holding a filled ArrowArrayStream.
#' @returns An integer vector: `c(length, first_value)`.
#' @export
`import_test_series` <- function(`stream_ptr`) {
  .Call(savvy_import_test_series__impl, `stream_ptr`)
}

### wrapper functions for RModel

`RModel_add_graph` <- function(self) {
  function(`other`, `source_graph` = NULL, `target_graph` = NULL) {
    `other` <- .savvy_extract_ptr(`other`, "maplibr::RModel")
    invisible(.Call(savvy_RModel_add_graph__impl, `self`, `other`, `source_graph`, `target_graph`))
  }
}

`RModel_add_prefixes` <- function(self) {
  function(`prefixes`) {
    invisible(.Call(savvy_RModel_add_prefixes__impl, `self`, `prefixes`))
  }
}

`RModel_compact` <- function(self) {
  function() {
    invisible(.Call(savvy_RModel_compact__impl, `self`))
  }
}

`RModel_create_index` <- function(self) {
  function() {
    invisible(.Call(savvy_RModel_create_index__impl, `self`))
  }
}

`RModel_detach_graph` <- function(self) {
  function(`preserve_name`, `graph` = NULL) {
    .savvy_wrap_RModel(.Call(savvy_RModel_detach_graph__impl, `self`, `preserve_name`, `graph`))
  }
}

`RModel_infer_rdfs` <- function(self) {
  function(`graph` = NULL) {
    .Call(savvy_RModel_infer_rdfs__impl, `self`, `graph`)
  }
}

`RModel_reads` <- function(self) {
  function(`s`, `format`, `graph` = NULL) {
    invisible(.Call(savvy_RModel_reads__impl, `self`, `s`, `format`, `graph`))
  }
}

`RModel_serialize` <- function(self) {
  function(`path`) {
    invisible(.Call(savvy_RModel_serialize__impl, `self`, `path`))
  }
}

`RModel_size` <- function(self) {
  function() {
    .Call(savvy_RModel_size__impl, `self`)
  }
}

`RModel_truncate_graph` <- function(self) {
  function(`graph` = NULL) {
    invisible(.Call(savvy_RModel_truncate_graph__impl, `self`, `graph`))
  }
}

`RModel_writes` <- function(self) {
  function(`format` = NULL, `graph` = NULL) {
    .Call(savvy_RModel_writes__impl, `self`, `format`, `graph`)
  }
}

`.savvy_wrap_RModel` <- function(ptr) {
  e <- new.env(parent = emptyenv())
  e$.ptr <- ptr
  e$`add_graph` <- `RModel_add_graph`(ptr)
  e$`add_prefixes` <- `RModel_add_prefixes`(ptr)
  e$`compact` <- `RModel_compact`(ptr)
  e$`create_index` <- `RModel_create_index`(ptr)
  e$`detach_graph` <- `RModel_detach_graph`(ptr)
  e$`infer_rdfs` <- `RModel_infer_rdfs`(ptr)
  e$`reads` <- `RModel_reads`(ptr)
  e$`serialize` <- `RModel_serialize`(ptr)
  e$`size` <- `RModel_size`(ptr)
  e$`truncate_graph` <- `RModel_truncate_graph`(ptr)
  e$`writes` <- `RModel_writes`(ptr)

  class(e) <- c("maplibr::RModel", "RModel", "savvy_maplibr__sealed")
  e
}


#' A maplib knowledge graph model.
#'
#' @export
`RModel` <- new.env(parent = emptyenv())

### associated functions for RModel

`RModel`$`deserialize` <- function(`path`, `storage_folder` = NULL) {
  .savvy_wrap_RModel(.Call(savvy_RModel_deserialize__impl, `path`, `storage_folder`))
}

`RModel`$`new` <- function() {
  .savvy_wrap_RModel(.Call(savvy_RModel_new__impl))
}


class(`RModel`) <- c("maplibr::RModel__bundle", "savvy_maplibr__sealed")

#' @export
`print.maplibr::RModel__bundle` <- function(x, ...) {
  cat('maplibr::RModel\n')
}

